### PR TITLE
Automatically remove todo item with no content

### PR DESCRIPTION
**Pull request by samyakvaidya10**
This PR fixes [issue no. 37](https://github.com/upnotes-io/react-todo/issues/37) .

https://user-images.githubusercontent.com/99262565/194704157-ce8cbfde-cfc7-49b4-b2ca-c756724af59b.mp4

### CODE REVIEW

**Comment by kamalkishor1991** [comment]
@samyakvaidya10 it should only get removed if back button is pressed and also it back button is pressed with text the text should merge with previous item.

**Comment by kamalkishor1991** [comment]
@samyakvaidya10 closing this because of lack in activity. Please create a new PR or reopen if you are still working on this.

**Comment by samyakvaidya10** [comment]
> @samyakvaidya10 closing this because of lack in activity. Please create a new PR or reopen if you are still working on this.

I apologize for showing a lack of inactivity and not giving a response. 
 
> @samyakvaidya10 it should only get removed if back button is pressed and also it back button is pressed with text the text should merge with previous item.

In the last few days, I'm clearing my basic concepts of react and still I'm not sure if ill be able to solve this issue. I'll open a new pr when I come up with some solution.
Thanks.

**Comment by kamalkishor1991** [comment]
@samyakvaidya10 no issues. Good luck 👍

**Comment by HarshithaSivalingala** [comment]
> @samyakvaidya10 it should only get removed if back button is pressed and also it back button is pressed with text the text should merge with previous item.

Hey, Can you explain what back button is , is it backspace ? , And also, Can you please provide the clear explanation ?

**Pull request closed without merging**
